runtime: python310

entrypoint: gunicorn -b :$PORT d29_frontend.flask_app:tpf2_app

handlers:
  - url: /static
    static_dir: d29_frontend/flask_app/static

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "google-cloud-tokyo.json"
  #  SERVER_URL: "https://tpf-server-tokyo.crazyideas.co.in/"
  SERVER_URL: "call_local"
  ENVIRONMENT: "prod"
  DOMAIN: "general"
  CI_CLOUD_STORAGE: "use"
